controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0

    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

      desired_linear_vel: 0.25
      max_linear_vel: 0.4
      min_linear_vel: 0.05

      max_angular_vel: 1.0
      lookahead_dist: 0.6
      use_velocity_scaled_lookahead_dist: true

      transform_tolerance: 0.2
      rotate_to_heading_angular_vel: 0.8

      allow_reversing: false
